language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WPdVjbh9GjpdE8u72SuE4klwiCh2rIXIkR+sZg/BARWD+0cjDkDpIHD+VB48vRTkCSgl0xH37KNZNq7I6fFleOgqqPqR7i4tZPQ3h6OTydjaqaUHZAnWU3ISnxhq/aSEwyS14nLueboJFdD9A7C91u4Ac3qopZx4loT0J7vW88jKEPgvk3Y7NRYSE/9fFLbczDrEqvOEqLSuqz4oHNyqh2zXEKhwMvOpf8k21ozBSqW7fmk7x8ZeQ+uT/tDREA6xsQL4yJCKjyFW6jmsdVEkGqsFS4yFTRDJLdHqEVk+ur0xK43FrLaf9mTE7hjI7EMa/A5FKyplmyY0DOVpahVfCFpAl1mPUg+70+FktsBuKr63gsQ2DJh1JpkU6deNih7Nep0oQHYIHl5EsAykJoOhQcchB0hNWUfipuLUrq1/0o5JketZF0hbtioABaZJlPlgdXttNKsKXsVdyORf1zTicLkj5kbLXHhu+cs/UayctwcfBaMAXboa2CGdzXVh0cWwElIXPzAojJfFGbglU5xBSOQstlmkgkspDu0CH5X2DjCyR026jHLdZY2iuamGFHnE+eP9bMosSd3hC6Iiu/0/0ACtfzqT+EP0VLIM4ceLcHWn9G3y5Y6udv9MlPcjzrPDN6Rk4Lve/0bRwzP7tNMuftVlLuLTCGSQrIV0nVi+5gU=
  app: glacial-hamlet-72363
  on:
    repo: thien-pham/node-shopping-list-integration-tests-2
